In [26]:
import numpy as np

In [27]:
    board = np.zeros((48, 8), dtype=int)

    # board[1::4, 0] = 2
    # board[:5, :] = 2
    # board[-5:, :] = 2

    board[1::4, 0] = 1
    board[:5, :] = 1
    board[-4:, :] = 1
    board[1:5, [3, 4]] = 0
    board[-5:, [3, 4]] = 0
    board[1, 3] = 1
    board[-3, 3] = 1

In [28]:
board[16,3]=1
board[17,3]=1
board[18,3]=1
board[19,3]=1
board[16,4]=1
board[21,5]=1
board[22,4]=1
board[17,1]=1
# board[10,4]=1
board[2,4]=1
board[7,4]=1
board[4,3]=1
board[1,4]=1
board[3,4]=1

In [29]:
# board[::4,:]
board

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0,

In [41]:
    board2 = np.zeros((48, 8), dtype=int)
    board2[1::4, 0] = 1
    board2[:5, :] = 1
    board2[-4:, :] = 1
    board2[1:5, [3, 4]] = 0
    board2[-5:, [3, 4]] = 0
    board2[1, 3] = 1
    board2[-3, 3] = 1
    for i in range(5,42):
        for j in range(8):
            if i%4 == 1:
                if j == 0:
                    board2[i, j] = 1
                else:
                    board2[i, j] = board[46-i, 8-j]
            elif i%4 == 2:
                board2[i + 2, j] = board[46-i , 7-j]
            elif i%4 == 0:
                board2[i+ 2, j] = board[46-i , 7-j]
            elif i%4 == 3:
                board2[i + 4, j] = board[46-i , 7-j]
                
    board2[44,3] = board[4,4]
    board2[44,4] = board[4,3]
    board2[45,4] = board[1,4]
    board2[46,3] = board[2,4]
    board2[46,4] = board[2,3]
    board2[47,3] = board[3,4]
    board2[47,4] = board[3,3] 
    
    board2[4, 4] = board[44,3]
    board2[4, 3] = board[44,4]
    board2[1, 4] = board[45,4]
    board2[2, 4] = board[46,3]
    board2[2, 3] = board[46,4]
    board2[3, 4] = board[47,3]
    board2[3, 3] = board[47,4] 

In [42]:
board2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1],
       [0,

In [43]:
board2[44,:]

array([1, 1, 1, 0, 1, 1, 1, 1])

In [44]:
    def get_positions(x, y):
        position1 = [0, 0]
        position2 = [0, 0]
        position1[1] = x
        if y % 4 == 0:
            position2[1] = x+1
            position1[0] = int(y/4)
            position2[0] = int(y/4)
        elif y % 4 == 1:
            position2[1] = x
            position1[0] = int(y/4)
            position2[0] = int(y/4+1)
        elif y % 4 == 2:
            position2[1] = x+1
            position1[0] = int(y/4)
            position2[0] = int(y/4)+1
        elif y % 4 == 3:
            position2[1] = x+1
            position1[0] = int(y/4)+1
            position2[0] = int(y/4)
        return position1, position2

    def get_all_lines(board):
        lines = []
        for i in range(48):
            for j in range(8):
                if board[i, j] == 1:
#                     print(j,i)
                    lines.append(get_positions(j, i))
        return lines

In [45]:
get_all_lines(board2)

[([0, 0], [0, 1]),
 ([0, 1], [0, 2]),
 ([0, 2], [0, 3]),
 ([0, 3], [0, 4]),
 ([0, 4], [0, 5]),
 ([0, 5], [0, 6]),
 ([0, 6], [0, 7]),
 ([0, 7], [0, 8]),
 ([0, 0], [1, 0]),
 ([0, 1], [1, 1]),
 ([0, 2], [1, 2]),
 ([0, 3], [1, 3]),
 ([0, 5], [1, 5]),
 ([0, 6], [1, 6]),
 ([0, 7], [1, 7]),
 ([0, 0], [1, 1]),
 ([0, 1], [1, 2]),
 ([0, 2], [1, 3]),
 ([0, 5], [1, 6]),
 ([0, 6], [1, 7]),
 ([0, 7], [1, 8]),
 ([1, 0], [0, 1]),
 ([1, 1], [0, 2]),
 ([1, 2], [0, 3]),
 ([1, 5], [0, 6]),
 ([1, 6], [0, 7]),
 ([1, 7], [0, 8]),
 ([1, 0], [1, 1]),
 ([1, 1], [1, 2]),
 ([1, 2], [1, 3]),
 ([1, 5], [1, 6]),
 ([1, 6], [1, 7]),
 ([1, 7], [1, 8]),
 ([1, 0], [2, 0]),
 ([2, 0], [3, 0]),
 ([3, 0], [4, 0]),
 ([4, 0], [5, 0]),
 ([5, 0], [6, 0]),
 ([6, 0], [7, 0]),
 ([6, 3], [7, 3]),
 ([6, 3], [7, 4]),
 ([7, 0], [8, 0]),
 ([7, 5], [8, 5]),
 ([7, 7], [8, 7]),
 ([7, 4], [8, 5]),
 ([8, 4], [7, 5]),
 ([8, 3], [8, 4]),
 ([8, 4], [8, 5]),
 ([8, 0], [9, 0]),
 ([9, 0], [10, 0]),
 ([10, 0], [11, 0]),
 ([11, 3], [10, 4]),
 ([11, 

In [46]:
get_all_lines(board)

[([0, 0], [0, 1]),
 ([0, 1], [0, 2]),
 ([0, 2], [0, 3]),
 ([0, 3], [0, 4]),
 ([0, 4], [0, 5]),
 ([0, 5], [0, 6]),
 ([0, 6], [0, 7]),
 ([0, 7], [0, 8]),
 ([0, 0], [1, 0]),
 ([0, 1], [1, 1]),
 ([0, 2], [1, 2]),
 ([0, 3], [1, 3]),
 ([0, 4], [1, 4]),
 ([0, 5], [1, 5]),
 ([0, 6], [1, 6]),
 ([0, 7], [1, 7]),
 ([0, 0], [1, 1]),
 ([0, 1], [1, 2]),
 ([0, 2], [1, 3]),
 ([0, 4], [1, 5]),
 ([0, 5], [1, 6]),
 ([0, 6], [1, 7]),
 ([0, 7], [1, 8]),
 ([1, 0], [0, 1]),
 ([1, 1], [0, 2]),
 ([1, 2], [0, 3]),
 ([1, 4], [0, 5]),
 ([1, 5], [0, 6]),
 ([1, 6], [0, 7]),
 ([1, 7], [0, 8]),
 ([1, 0], [1, 1]),
 ([1, 1], [1, 2]),
 ([1, 2], [1, 3]),
 ([1, 3], [1, 4]),
 ([1, 5], [1, 6]),
 ([1, 6], [1, 7]),
 ([1, 7], [1, 8]),
 ([1, 0], [2, 0]),
 ([2, 4], [1, 5]),
 ([2, 0], [3, 0]),
 ([3, 0], [4, 0]),
 ([4, 3], [4, 4]),
 ([4, 4], [4, 5]),
 ([4, 0], [5, 0]),
 ([4, 1], [5, 1]),
 ([4, 3], [5, 3]),
 ([4, 3], [5, 4]),
 ([5, 3], [4, 4]),
 ([5, 0], [6, 0]),
 ([5, 5], [6, 5]),
 ([5, 4], [6, 5]),
 ([6, 0], [7, 0]),
 ([7, 0], [8